# Generated by Django 4.2.20 on 2025-03-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_remove_patient_patient_age_patient_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
