# Generated by Django 4.2.20 on 2025-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_doctor_doctor_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appoinment_completed',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appoinment_booking_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Confirmed', max_length=30),
        ),
    ]
