# Generated by Django 4.2.20 on 2025-03-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_remove_appointment_appoinment_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appoinment_booking_status',
            new_name='booking_status',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appoinment_doctor_remarks',
            new_name='doctor_remarks',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_dob',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_image',
            new_name='image',
        ),
    ]
