# Generated by Django 4.2.20 on 2025-03-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_rename_appoinment_booking_status_appointment_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='id',
            new_name='doctor_id',
        ),
    ]
