version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt pylint
  pre_build:
    commands:
      - python --version
      - pylint --exit-zero $CODEBUILD_SRC_DIR/*.py
      - pylint --exit-zero $CODEBUILD_SRC_DIR/doctor_project/*.py
      - pylint --exit-zero $CODEBUILD_SRC_DIR/doctor_app/*.py
      # - yum update -y
      # - yum -y install jq
      # - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      # - tar xzf apache-maven-3.5.4-bin.tar.gz
      # - ln -s apache-maven-3.5.4 maven
      # - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      # - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      # - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/

  build:
    commands:
      - echo "Running tests..."
      - pytest --junitxml=report.xml  
      - echo "Building project..."
      - zip -r application.zip . 
      #  - echo "Running sonar qube..."
      # - mvn test     
      # - mvn sonar:sonar -Dsonar.login=69e600e4f48c3e6b99da460589b4cb8f5dcc6d8d -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.projectKey=x23286873_cloud_devops_sec -Dsonar.organization=nidhianandan12
      # - sleep 5
      # - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=x23286873_cloud_devops_sec >result.json
      # - cat result.json
      # - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
artifacts:
  files:
    - '**/*'
    - report.xml
