# Generated by Django 4.2.20 on 2025-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_age',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_dob',
            field=models.DateField(default=None),
        ),
    ]
