# Generated by Django 4.2.20 on 2025-03-08 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_alter_patient_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
